[package]
name = "invoice-proxy"
version = "0.1.0"
authors = ["Stan Rozenraukh <stan@stanistan.com>"]
edition = "2018"

[dependencies]
airtable-proxy = { path = "airtable-proxy" }
serde = { version = "1.0", features = ["derive"] }
num-format = "0.4.0"
